apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-config.yaml
  - postgres-pvc.yaml
  - postgres-keyvault.yaml # Updated to use Key Vault integration
  - backend-config.yaml
  - backend-keyvault.yaml # Updated to use Key Vault credentials
  - frontend-config.yaml
  - frontend.yaml
  - key-vault-secrets.yaml

namespace: 3tirewebapp-dev

commonLabels:
  app.kubernetes.io/name: 3tirewebapp
  app.kubernetes.io/part-of: 3tirewebapp

images:
  - name: itsbaivab/frontend
    newTag: v2
  - name: itsbaivab/backend
    newTag: latest
